#ifndef TERMINALES_H_INCLUDED
#define TERMINALES_H_INCLUDED

#define TERMINADOR_PUNTOCOMA_INDEX 0 
#define TERMINADOR_ENTER_INDEX 1
#define L_PARENTESIS_INDEX 2
#define R_PARENTESIS_INDEX 3
#define OP_CONDICION_INDEX 4
#define OP_SUMA_INDEX 5
#define OP_MUL_INDEX 6
#define OP_RELACIONAL_INDEX 7
#define OP_ASIGNACION_INDEX 8 
#define L_CORCHETE_INDEX 9
#define R_CORCHETE_INDEX 10
#define COMA_INDEX 11
#define DELIMITADOR_CODIGO_INDEX 12
#define PR_IF_INDEX 13
#define PR_TRUE_INDEX 14
#define PR_FALSE_INDEX 15
#define PR_ALERT_INDEX 16
#define LITERAL_NUM_INDEX 17
#define LITERAL_CADENA_INDEX 18 
#define ID_INDEX 19
#define COMMENT_INDEX 20 
#define _EOF_INDEX 21
#define __ERROR_INDEX -1

#endif
